my_hubu/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('topic.urls')),
    path('user/',include('users.urls')),
    re_path(r'mdeditor/', include('mdeditor.urls')),
    re_path(r'^accounts/',include('allauth.urls')),
    re_path('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
    re_path(r'^articles/comments/', include('django_comments.urls')),
     path(
        "ads.txt",
        RedirectView.as_view(url=staticfiles_storage.url("ads.txt")),
    ),


]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

topic/urls.py
from django.contrib import admin
from django.urls import path,include,re_path

from .views import  indexView,PostContentView,writePostView,selectPostAjaxView,ajaxDraftsView,ajaxDraftsContentView,EmailSettingsView,ads
from  .views import NewProfileView,notificationView,allCommentList,DraftsView,Sort_View,searchPostView,postSuccess,apiAllPost,apiAllPostRecommend,apiGetPost,apiGetSort,apiGetSortContent,getCarousel
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
app_name="topic"

urlpatterns = [
    path('',indexView.as_view(),name="index"),
    re_path('ads.txt',ads,name="ads"),
    path('drafts/<str:type>/', DraftsView.as_view(), name="drafts"),
    path('postContent/<str:postId>/<str:slug>/',PostContentView.as_view(),name="postContent"),
    path('writePost/<str:type>/',writePostView.as_view(),name="writePost"),
    path('api/selectPost/',selectPostAjaxView,name="AjaxPost"),
    path('api/drafts/',ajaxDraftsView.as_view(),name="writeDrafts"),
    path('api/drafts/<str:draftsId>/',ajaxDraftsContentView.as_view(),name="writeDraftsContent"),
    path('settings/email/',EmailSettingsView.as_view(),name="emailSettings"),
    path('accounts/profile/',NewProfileView.as_view(),name="new_profile"),
    path('api/notifications/',notificationView,name="notifications"),
    path('api/allCommentList/',allCommentList,name="allCommentList"),
    path('sort/',Sort_View.as_view(),name='Sort'),
    path('sort/<int:node_id>/',Sort_View.as_view(),name='SortContent'),
    path('search/',searchPostView,name='searchContent'),
    path('success/<str:username>/',postSuccess,name='postSuccess'),   
    path('api/allPost/',apiAllPost,name='apiAllpost'),
    path('api/allPost/recommend/',apiAllPostRecommend,name='apiAllPostRecommend'),
    path('api/getPost/',apiGetPost,name='apiGetPost'),
    path('api/getSort/',apiGetSort,name='apiGetSort'),
    path('api/getSortContent/',apiGetSortContent,name='apiGetSortContent'),
    path('api/getCarousel/',getCarousel,name='getCarousel'),


]

users/urls.py
from django.contrib import admin
from django.urls import path,include

app_name="users"

from .views import  notificationView,editProfile,editProfileApi,uploadPicture,agreeView,lookUserProfile
from  .views import  follow,profileFollow
urlpatterns = [
    path('notification/',notificationView.as_view(),name="notification"),
    path('editProfile/',editProfile, name="editProfile"),
    path('api/editProfile/',editProfileApi,name="editProfileApi"),
    path('api/uploadPicture/',uploadPicture,name="uploadPicture"),
    path('api/agreebutton/',agreeView,name="agreebutton"),
    path('profile/<int:id>/',lookUserProfile,name="lookProfile"),
    path('api/follow/',follow,name='follow'),
    path('api/profileFollow/',profileFollow,name='profileFollow'),

]
















topic/models.py
from django.db import models
from  django.core.validators import MaxValueValidator,MinValueValidator
#####
from  mdeditor.fields import MDTextField
#####
from  PIL  import Image
from  users.models import User_Info

from  bs4  import BeautifulSoup

from slugify  import slugify
# Create your models here.
from notifications.models import Notification
#signal信号
from  django.db.models.signals import post_delete,post_save
from notifications.signals import notify
from  imagekit.models  import  ProcessedImageField
from imagekit.processors import ResizeToFill
import  mistune
from lxml.html.clean import clean_html
import os
import re
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))



class  Sort_Model(models.Model):
    """
    2019/01/20
    重写分类，与文章一对一关系
    2019/01/24
    对分类进行更新，更新为板块
    """
    name = models.CharField(max_length=30,verbose_name='文章分类/板块（内部）')
    node = models.CharField(max_length=20,verbose_name='文章分类/板块（外部）')
    manager = models.ForeignKey(User_Info,on_delete=models.CASCADE,verbose_name="板块管理人")
    parent = models.ForeignKey('self', on_delete=models.CASCADE,blank=True, null=True, related_name='childcolumn')
    description = models.TextField(verbose_name='板块描述')
    sort_img = ProcessedImageField(upload_to='sort/%Y/%m', default='image/timg.jpg',
                                 processors=[ResizeToFill(40, 40)], format='JPEG', options={'quality': 100},
                                 verbose_name='分类图标', max_length=300, blank=True, null=True,
                                 height_field='sort_imgHeight', width_field='sort_imgWeight')
    sort_imgWeight = models.PositiveIntegerField(default=150, verbose_name="个人头像宽度")
    sort_imgHeight = models.PositiveIntegerField(default=150, verbose_name="个人头像高度")

    post_number = models.IntegerField(default=0)
    pub_time = models.DateTimeField(auto_now_add=True, verbose_name="分类序号(用时间区分)")
    updated_time = models.DateTimeField(auto_now=True, verbose_name="更新板块时间")
    class  Meta:
        verbose_name='板块'
        verbose_name_plural=verbose_name
        ordering=["pub_time",]

    def  __str__(self):
        return  self.node





class  Create_Topic_Model(models.Model):
    """
    2019/01/20,重新设计文章模型
    2019/01/24,重写外键
    """
    user=models.ForeignKey(User_Info,on_delete=models.CASCADE,verbose_name="作者")

    node = models.ForeignKey(Sort_Model, on_delete=models.CASCADE,verbose_name="文章分类")

    title = models.CharField(max_length=200, verbose_name='标题')
    
    zhihu_id = models.CharField(verbose_name="是否为知乎文章", max_length=500, null=True, blank=True)

    draft_pk = models.CharField(verbose_name="草稿id", max_length=500,null=True,blank=True)

    content = MDTextField(verbose_name='文章内容(html版)')

    pub_time = models.DateTimeField(auto_now_add=True,verbose_name="发布时间")

    read_nums = models.IntegerField(default=0, verbose_name=u"阅读次数")
    pictureUrl=models.CharField(max_length=200,verbose_name="文章样图",blank=True,null=True)

    update_time = models.DateTimeField(auto_now=True,verbose_name="修改时间",)
    top = models.IntegerField(validators=[MaxValueValidator(1),MinValueValidator(0)], default='0', blank=True, verbose_name="是否置顶(1表示置顶)",null=True)
    slug=models.SlugField(max_length=200,verbose_name="短标签",null=True,blank=True)
    agree=models.PositiveIntegerField(default=0,verbose_name="点赞次数")
    class  Meta:
        verbose_name='发表文章'
        verbose_name_plural=verbose_name
        ordering=('-pub_time',)

    def  __str__(self):
        return  str(self.title)

    # 使用方法统计阅读次数
    def increase_views(self):
        self.read_nums += 1
        self.save(update_fields=['read_nums'])
    #     获取文章中的图片地址
    def  getPostPictureUrl(self):
        value = clean_html(mistune.markdown(self.content))
        soup=BeautifulSoup(value,'html.parser')
        try:
            img = soup.find_all('img')
            src = img[0].get('src')
            src1 = str(src).replace('editor/', 'post/')
            self.pictureUrl=src1
            self.save()
            src = str(src).split('/')[3]
            pictureUrl1 = os.path.join(BASE_DIR, 'uploads', 'editor', src)
            im = Image.open(pictureUrl1)
            newIm = im.copy()
            newIm.thumbnail((200, 110),Image.ANTIALIAS)
            b = os.path.join(BASE_DIR, 'uploads', 'post', src)
            newIm.save(b)
        except:
            self.pictureUrl="无"
            self.save()
    def updatePictureUrl(self):
        content=self.content
        newText = re.findall(r'!\[\]\((.*)\)', content)
        for eachText in newText:
            content = content.replace(str(eachText), str('http://www.biocoder.cn' + eachText))
        self.content=content

    def  save(self,*args,**kwargs):
        self.slug=slugify(self.title)
        super(Create_Topic_Model,self).save(*args,**kwargs)
    def increase_agree(self):
        self.agree += 1
        self.save(update_fields=['agree'])



class  Carousel_Model(models.Model):
    title = models.CharField(max_length=50, verbose_name='轮播标题')
    post=models.ForeignKey(Create_Topic_Model,on_delete=models.CASCADE,verbose_name="关联文章")
    slug= models.CharField(max_length=500, verbose_name='轮播内容')
    update_at=models.DateTimeField(auto_now=True,verbose_name="生成时间")
    avatar = ProcessedImageField(upload_to='carousel/%Y/%m', default='image/timg.jpg',
                                 processors=[ResizeToFill(800, 250)], format='JPEG', options={'quality': 100},
                                 verbose_name='轮播图片', max_length=300, blank=True, null=True,
                                 height_field='avatarHeight', width_field='avatarWeight')
    avatarWeight = models.PositiveIntegerField(default=800, verbose_name="个人头像宽度")
    avatarHeight = models.PositiveIntegerField(default=250, verbose_name="个人头像高度")
    class  Meta:
        verbose_name='轮播内容'
        verbose_name_plural=verbose_name
        ordering=["-update_at",]

    def  __str__(self):
        return  self.title



# class  DraftsModel(models.Model):
#     """
#     1/20,还未考虑用户外键
#     1/24更新，加入用户外键
#     """
#     user = models.ForeignKey(User_Info, on_delete=models.CASCADE, verbose_name="作者")
#     draft_pk=models.CharField(verbose_name="草稿id",max_length=500)
#
#     title = models.CharField(max_length=200, default='无标题',verbose_name='草稿标题')
#     content = models.TextField(verbose_name='草稿内容')
#     update_time = models.DateTimeField(auto_now=True, verbose_name="草稿修改时间")
#
#     class  Meta:
#         verbose_name='草稿箱'
#         verbose_name_plural=verbose_name
#         ordering=('-update_time',)
#
#     def  __str__(self):
#         return  str(self.id)
# class Message(models.Model):
#     # 好友消息
#     sender = models.ForeignKey(User_Info, related_name='message_sender')  # 发送者
#     receiver = models.ForeignKey(User_Info, related_name='message_receiver')  # 接收者
#     content = models.TextField()
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)
#
#     def description(self):
#         return "{}给你发送了消息{}".format(self.sender, self.content)
#
#     class Meta:
#         db_table = 'message'
#         verbose_name_plural = u'消息'

class  AgreeModel(models.Model):
    """
    点赞model 2019/1/31
    """
    user=models.ForeignKey(User_Info,on_delete=models.CASCADE,verbose_name="点赞用户")
    post=models.ForeignKey(Create_Topic_Model,on_delete=models.CASCADE,verbose_name="被点赞的文章")
    agreeTime=models.DateTimeField(auto_now_add=True,verbose_name="点赞时间")
    status=models.PositiveIntegerField(default=0,validators=[MaxValueValidator(1)],verbose_name="是否已读")
    class  Meta:
        verbose_name='点赞模块'
        verbose_name_plural=verbose_name

    def  __str__(self):
        return  self.status

    def statisticsAgree(self,*args,**kwargs):
        realUser=User_Info.objects.get(username=self.post.user.username)
        realUser.agreeNumber+=1
        realUser.allGoodBlogerNum+=1
        realUser.save()

def Agree_Save(sender, instance,**kwargs):
    receiver = instance.post.user
    # if instance.post.user.username!=instance.user.username:
    #     instance.statisticsAgree()
    notify.send(sender=instance.user,recipient=receiver,verb="文章点赞",description=instance.post.title)



post_save.connect(Agree_Save,sender=AgreeModel)


topic/forms.py
from  django  import   forms
from .  import  models

class Create_Topic_Form(forms.ModelForm):
    """
    2019/1/20,重写创建文章表单
    """
    class Meta:
        model =models.Create_Topic_Model
        fields = ('title','content',)
        error_messages={
            'title':{'required':'您未输入标题'},
            'content':{'requires':'请输入内容'}
                        }#数据格式为json格式
        widgets = {'title': forms.TextInput(attrs={"class": "form-control input-lg","style":"width: 900px;","placeholder":"输入文章标题..."}),}

templates/topic/allCommentList.html
{% load threadedcomments_tags %}

{% render_comment_list for getPost %}

templates/topic/allDrafts.html
{% load  staticfiles %}
{% load  newhubu %}
{% for eachDraft  in  allDrafts %}
      <div class="item">
      <div class="item-heading">
          <h3><a  href="{% url  'topic:drafts' type='edit' %}?draft_id={{ eachDraft.id }}" target="_blank">{{ eachDraft.title }}</a></h3>
      </div>
          <div class="item-content">
              {% CutContent  eachDraft.content %}
          </div>
      <div class="item-footer" value="{{ eachDraft.id }}">
          <a  href="javascript:void (0);" class="text-muted draft-delete">删除</a>

          <span class="Footer-dot"></span>
          <a href="{% url  'topic:drafts' type='edit' %}?draft_id={{ eachDraft.id }}" class="text-muted  draft-edit">编辑</a>

          <span class="Footer-dot"></span>
         保存时间{{ eachDraft.update_time }}
          <span class="Footer-dot"></span>
           共 {{ eachDraft.content|length }} 字
          <span class="Footer-dot"></span>
          文章
      </div>
    </div>
      {% endfor %}

templates/topic/index.html
{% extends  'myAPPBase.html' %}
{% load  staticfiles %}
{% load  newhubu %}
{% load  threadedcomments_tags %}

{% block CssOrJs %} 

 {% endblock %}




{% block  right-container %}


    <div  class="row">
{#        <h1  id="carousel-title">生物信息热点：“贺建奎”让基因编辑“背了个大锅”</h1>#}
<div id="myNiceCarousel" class="carousel slide" data-ride="carousel">
<ol class="carousel-indicators">
    <li data-target="#myNiceCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myNiceCarousel" data-slide-to="1"></li>
    <li data-target="#myNiceCarousel" data-slide-to="2"></li>
  </ol>
 <!-- 轮播项目 -->
  <div class="carousel-inner">
      {% for  eachCarousel  in allCarousel %}
          {% ifequal  forloop.counter  1 %}
    <div class="item active">
    <a  href="{% url  'topic:postContent' postId=eachCarousel.post.id slug=eachCarousel.post.slug %}">
    <h1>{{ eachCarousel.title }}</h1>
      <img alt="{{ eachCarousel.title }}" src="{{ eachCarousel.avatar.url }}">
      <div class="carousel-caption">
        <h3>{{ eachCarousel.title }}</h3>
        <p>{{ eachCarousel.slug }}</p>
      </div>
    </a>
    </div>
              {% else %}
              <div class="item">
              <a  href="{% url  'topic:postContent' postId=eachCarousel.post.id slug=eachCarousel.post.slug %}">
              <h1>{{ eachCarousel.title }}</h1>
      <img alt="{{ eachCarousel.title }}" src="{{ eachCarousel.avatar.url }}">
      <div class="carousel-caption">
        <h3>{{ eachCarousel.title }}</h3>
        <p>{{ eachCarousel.slug }}</p>
      </div>
              </a>
    </div>
          {% endifequal %}
{% endfor %}
  </div>

  <!-- 项目切换按钮 -->
  <a class="left carousel-control" href="#myNiceCarousel" data-slide="prev">
    <span class="icon icon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#myNiceCarousel" data-slide="next">
    <span class="icon icon-chevron-right"></span>
  </a>
</div>
    <!-------------轮播结束----------------------->
    </div>
    <div class="row">
<div class="list">
  <header>
      <h3><a id="recommend" href="javascript:void (0);" class="color-index"> 推荐 </a>
        <span id="newNew">
            <a href="javascript:void (0);"> 最新 <small></small></a>
        </span>
          <span id="top">
            <a style='margin-left: 10px;' href="javascript:void (0);"> 置顶 <small></small></a>
        </span>
    </h3>
  </header>
<span id="loading-number" style="display: none;">2</span>
<div  id="list-Content">
    {% for  eachPost  in  allPostList %}
        {% get_comment_count for eachPost as  commentCount %}
  <div class="items items-hover" id="leftContent" style="overflow: auto!important;line-height: 1.67;">
      <div class="item" style="font-size: 15px!important;">
      <div class="item-heading">
          <div style="font-size: 12px!important;" class="pull-right label label-success"><a href="{% url 'topic:SortContent'  node_id=eachPost.node.id  %}" style="color: #fff!important;">{{ eachPost.node }}</a></div>
        <h2><a style="color: #145ccd!important;" href="{% url  'topic:postContent' postId=eachPost.id slug=eachPost.slug %}" target='_blank'>{{ eachPost.title }}</a></h2>
      </div>
      <div class="item-content">
          <a  style="color: grey;" href="{% url  'topic:postContent' postId=eachPost.id slug=eachPost.slug %}">
         {% ifequal eachPost.pictureUrl  '无' %}
             {% else %}
              <div class="media pull-right card"  style="margin-left: 20px;"><img src="{{ eachPost.pictureUrl }}"  alt="{{ eachPost.title }}--HUBU生信社区www.biocoder.cn"></div>
          {% endifequal %}
              <div class="text"><a style="color: #1A1A1A;font-size: 14px;" href="{% url  'topic:postContent' postId=eachPost.id slug=eachPost.slug %}">{% CutContent  eachPost.content %}</a></div>
          </a>
      </div>

      <div class="item-footer">
          <a href="{% url  'users:lookProfile' id=eachPost.user.id %}" class="text-muted"><i style="font-size: 14px!important;" class="icon icon-user"></i>{{ eachPost.user.nick_name }}</a>
          <div  class="pull-right">
              <span><a  href="{% url  'topic:postContent' postId=eachPost.id slug=eachPost.slug %}" class="text-muted"><i style="font-size: 14px!important;" class="icon icon-eye-open"></i> {{ eachPost.read_nums }}</a> </span><span><a href="{% url  'topic:postContent' postId=eachPost.id slug=eachPost.slug %}#defaultComment" class="text-muted"><i style="font-size: 14px!important;" class="icon-chat"></i> {{ commentCount }}</a> </span><span style="font-size: 14px!important;" class="text-muted">{{ eachPost.update_time }}</span>

          </div>
          </div>
    </div>
  </div>
    {% endfor %}
<!--script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-format="fluid"
     data-ad-layout-key="-fc-o-4k-e1+1g6"
     data-ad-client="ca-pub-5072850497249913"
     data-ad-slot="3926895629"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script-->
</div>
{#<footer>#}
{#  <!--开始分页------------------>#}
{#      <div  class="row">#}
{#          <div  class="col-xs-12 col-md-offset-2">#}
{#<ul class="pager pager-justify pager-pills">#}
{#    <li><a  class="load-more" >阅读更多 </a></li>#}
{#    <span id="loading-number" style="display: none;">1</span>#}
{#  </ul>#}
{#          </div>#}
{#      </div>#}
{#    <!-------分页结束--------->#}
{#  </footer>#}
</div>
    </div>
{% endblock %}
{% block  left-container %}
<div class="panel">
  <div class="panel-body">
      <div class="row">
      <a class="panel-item" href="{% url  'topic:writePost'  type='create' %}">
   <i class="icon icon-edit"></i>
      <p>写文章</p>
      </a>
        <a class="panel-item" href="{% url  'topic:writePost'  type='create' %}">
   <i class="icon icon-question "></i>
      <br>
       <p>提问题</p>
      </a>
        <a class="panel-item" href="{% url  'topic:writePost'  type='create' %}">
   <i class="icon icon-gift"></i>
      <br>
      <p>写想法</p>
      </a>
      </div>
  </div>
   <div class="list-group">
       {% if request.user.is_authenticated %}
       <a href="{% url  'topic:drafts'  type='watch' %}" class="list-group-item"><i class="icon icon-bookmark-empty">草稿箱</i> <span class="label label-badge label-info" style="font-size: 14px;">{% getDratfsNumber request %}个草稿</span></a>
       {% else %}
        <a href="{% url 'account_login' %}" class="list-group-item"><i class="icon icon-bookmark-empty">草稿箱</i></a>

       {% endif %}
   </div>
</div>
    <!--------------------各项功能开始-------------------------------->
    <!--第二个面板开始--->
<div class="panel panel-info">
        <div class="panel-body">
            <p style="color: #333;font-size: 16px;border-bottom: solid 1px #ddd;">HUBU生信每周最佳博主</p>
  <div class="items">
      <!--排名第一-->
      {% for eachUser  in allGoodBloger %}
    <div class="item">
      <div class="item-content">
          <div class="media pull-left"><a href="{% url  'users:lookProfile'  id=eachUser.id %}"><img src="{{ eachUser.avatar.url }}" alt="{{ eachUser.nick_name }}的头像" width="46" height="46"></a></div>
          <div class="text" style="font-size: 14px;"><a  style="color: grey!important;" href="{% url  'users:lookProfile'  id=eachUser.id %}">{{ forloop.counter }}.{{ eachUser.nick_name }}</a></div>
          <p><a href="{% url  'users:lookProfile'  id=eachUser.id %}" target="_blank" style="    background: url(//assets.dxycdn.com/gitrepo/bbs/img/bbs/userrankflw.png?t=12) no-repeat;display: inline-block;
    width: 54px;
    height: 24px;"></a></p>
      </div>
    </div>
      {% endfor %}
      <!--一个结束-->

  </div>
</div>
</div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-format="fluid"
     data-ad-layout-key="-i3+e-1e-2w+ap"
     data-ad-client="ca-pub-5072850497249913"
     data-ad-slot="1109679455"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
    <!--第三个面板开始-->
    <div class="panel panel-info">
        <div class="panel-body">
            <p style="color: #333;font-size: 16px;border-bottom: solid 1px #ddd;">每周十大热门文章</p>
<div class="items">
    {% for  eachPost  in allGoodPost %}
        {% get_comment_count for eachPost as  commentCount %}
      <div class="item"  style="font-size: 15px!important;">
        <div class="item-heading">
          <h4><a href="{% url  'topic:postContent' postId=eachPost.id slug=eachPost.slug %}">{{ forloop.counter }}.{{ eachPost.title }}</a></h4>
        </div>
        <div class="item-content">
          <div class="text" style="font-size:12px;">{% CutContent  eachPost.content %}</div>
        </div>
        <div class="item-footer">
           <span class="text-muted" style="font-size: 14px!important;"><a  href="{% url  'users:lookProfile' id=eachPost.user.id %}"><i style="font-size: 14px!important;" class="icon icon-user"></i>{{ eachPost.user}}</a></span><span style="font-size:13px!important;" class="pull-right">{{ eachPost.update_time }}</span>
        </div>
      </div>
    {% endfor %}


</div>
</div>
    </div>


{#    <!----------广告轮播区------------->#}
{#    <!-----------ad结束---------------------->#}
{#    <!----热门问题-->#}
{#        <!--div class="panel panel-info">#}
{#        <div class="panel-body">#}
{#            <p style="color: #333;font-size: 16px;border-bottom: solid 1px #ddd;">每周十大热门问题</p>#}
{#  <div class="items">#}
{#     #}
{#    <div class="item">#}
{#        <div class="item-heading">#}
{#        <div class="pull-right label label-success">维基</div>#}
{#        <h4><a href="###">HTML5 发展历史</a></h4>#}
{#      </div>#}
{#    </div>#}
{#       <div class="item">#}
{#        <div class="item-heading">#}
{#        <div class="pull-right label label-success">维基</div>#}
{#        <h4><a href="###">HTML5 发展历史</a></h4>#}
{#      </div>#}
{#    </div>#}
{#       <div class="item">#}
{#        <div class="item-heading">#}
{#        <div class="pull-right label label-success">维基</div>#}
{#        <h4><a href="###">HTML5 发展历史</a></h4>#}
{#      </div>#}
{#    </div>#}
{#     #}
{#  </div>#}
{#</div>#}
{#    </div>#}
{#    #}
{#   #}
{# <div class="panel panel-info">#}
{#        <div class="panel-body">#}
{#            <p style="color: #333;font-size: 16px;border-bottom: solid 1px #ddd;">生物产业招聘专场<span style="float: right"><a  href="www">更多</a></span></p>#}
{#  <div class="items">#}
{#      <!---------------------->#}
{#    <div class="item">#}
{#        <div class="item-heading">#}
{#        <div class="pull-right label label-success">维基</div>#}
{#        <h4><a href="###">HTML5 发展历史</a></h4>#}
{#      </div>#}
{#    </div>#}
{#<!--------------------->#}
{#       <div class="item">#}
{#        <div class="item-heading">#}
{#        <div class="pull-right label label-success">维基</div>#}
{#        <h4><a href="###">HTML5 发展历史</a></h4>#}
{#      </div>#}
{#    </div>#}
{#       <div class="item">#}
{#        <div class="item-heading">#}
{#        <div class="pull-right label label-success">维基</div>#}
{#        <h4><a href="###">HTML5 发展历史</a></h4>#}
{#      </div>#}
{#    </div>#}
{#      <!---中间内容-->#}
{#  </div>#}
{#</div>#}
{#</div>#}
    <!------------------->
     <div class="container">
    <p style="margin-top: 0px;color:#878B91;font-size: 14px;line-height: 2;">
        HUBU生信专注于生物信息学技术发展的社区<br>
        <a  style="color:#878B91;" target="_blank" href="http://bio.hubu.edu.cn/">湖北大学生物信息学</a><span  class="Footer-dot"></span>
        <a  style="color:#878B91;" target="_blank" href="http://www.12377.cn/">网上有害信息举报专区</a><br>
        联系方式：anshiwang@yeah.net<br>
        Copyright ©<a  style="color:#878B91;" target="_blank" href="https://www.lovexu.xyz">我爱小徐子</a>    -基于<a  style="color:#878B91;" target="_blank" href="https://www.djangoproject.com/">django</a>开发
        </p>
  </div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-format="fluid"
     data-ad-layout-key="-i3+e-1e-2w+ap"
     data-ad-client="ca-pub-5072850497249913"
     data-ad-slot="1109679455"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>





    <!------------------------------->
    <!--脚注--->
{% endblock %}





